config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'welcome#index'
    
    mount ActionCable.server => '/cable'
	resources :users do
		resources :tasks do
			member do
				put :complete
				end
			end
    end
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable, :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	devise_parameter_sanitizer.permit(:account_update, keys: [:name])
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = current_user.tasks.all
  end
    def edit
    @task = User.find(params[:user_id]).tasks.find(params[:id])
  end
  
  
def create
    @task = current_user.tasks.create(task_params)
    respond_to do |format|
        format.html { redirect_to user_tasks_path(current_user)	, notice: 'Task was successfully created.' }
        format.js   {}
        format.json { render json: @task, status: :created, location: @task }    
    end
  #  ActionCable.server.broadcast "AsyncRequestChannel", { title: 'MANDANDO MSG', body: 'All the news that is fit to print' }
   # redirect_to user_tasks_path(current_user)	
  end
 
def complete
	#@user = User.find(params[:user_id])
	@task = Task.find(params[:id])
	if @task.update_attribute(:completed, params[:completed])
        create_task_completed_event
        TaskCompleteEmailJob.perform_async(@event)
		#flash[:success] = "Congratulations on completing a task! A VERY important email was sent to you :)"
	else
		#flash[:failure] = "Error, could not complete task"
	end
   respond_to do |format|
        format.html { redirect_to user_tasks_path(current_user)	, notice: 'Task was successfully completed.' }
        format.js   { }
        format.json { render json: @task, status: :completed, location: @task }    
    end
	#redirect_to user_tasks_path(current_user)	
end
 
  def update
	@task = Task.find(params[:id])
	@task.update_attribute(:completed, params[:completed])
	@task.update_attribute(:text, params[:task][:text])	
	redirect_to user_tasks_path(current_user)	
  end
  
  def destroy
      @task = Task.find(params[:id])
      @task.destroy
    respond_to do |format|
            format.html { redirect_to user_tasks_path(current_user)		, notice: 'Task was successfully deleted.' }
            format.js   {}
            format.json { render json: @task, status: :completed, location: @task }    
    end
  end
  
  private
	
	def create_task_completed_event
		infoValue ||= {}
		infoValue[:colour] = MYCOLOURS[rand(5)]
		infoValue[:phrase] = MYPHRASES[rand(5)]
		@event = Event.create(event_type: 'TaskComplete' , info: infoValue.to_json, task_id: params[:id])
		@event.save
	end
  
    def task_params
      params.require(:task).permit(:text, :completed)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
def header(text)
  content_for(:header) { text.to_s }
end
end

app/helpers/tasks_helper.rb
module TasksHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'ToDoList', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

<%= yield :top_content %>

<div class="container">
    <h1><%= yield :header %></h1>
  <%= yield %>
</div>
  

 
  </body>
</html>

app/views/messages/_message.html.erb
<p><%= message %></p>

app/views/tasks/_task.html.erb
<tr id="RowID_<%= task.id %>">
    
    <td><%= task.text %></td>
        <% if task.completed? %>
            <td>Done</td>
        <% else %>
        <td><%= link_to("Complete", complete_user_task_path(current_user,task,:completed => "TRUE"), method: :put, id: task.id, remote: true) %></td>

        <% end %>
        <td><%= link_to("Edit", edit_user_task_path(current_user,task)) %></td>
        <td><%= link_to("Delete", user_task_path(current_user,task), method: :delete,  data: { confirm: "Are you sure?" ,remote: true}) %></td>
</tr>

app/views/tasks/complete.js.erb
$("#success").html("<%= flash[:success] %>");
var MyTaskId = "#" + <%= @task.id %>;
$(MyTaskId).text("Done");
$(MyTaskId).contents().unwrap();

app/views/tasks/create.js.erb
$("<%= escape_javascript(render @task) %>").appendTo("#tasks");
$("#new_task_text").val('');

app/views/tasks/destroy.js.erb
var MyTaskRowId = "#RowID_" + <%= @task.id %>;
$(MyTaskRowId).remove();

app/views/tasks/edit.html.erb
<% content_for :top_content do %>

  <div class="jumbotron">
    <div class="container">	

		<h2>Edit the task:</h2>
		    <%= form_for :task, url: user_task_path(current_user,@task), method: :patch do |f| %>
			  <p>
				<%= f.label :text %><br>
				<%= f.text_area :text, :class  => 'form-control' %>
			  </p>			  
				<%= f.hidden_field :completed, :value => "FALSE" %>
			  <p>
				<%= f.submit %>
			  </p>
			<% end %>
			
   </div>
  </div>
<% end %>

app/views/tasks/index.html.erb
<% content_for :top_content do %>

  <div class="jumbotron">
    <div class="container">	

		<h1>Tasks</h1>
		 <table id="tasks" class="table table-striped table-bordered table-hover table-reflow">
		  <thead class="thead-inverse">
			<tr>
			  <th>Task</th>
			  <th width="40px" >Status</th>
			  <th width="40px"></th>
			  <th width="40px" ></th>
			</tr>
		  </thead>
            <%= render @tasks %>
	</table>

    
		<h2>Add a new task:</h2>

			<%= form_for [current_user, current_user.tasks.build], remote: true, :html => {'class' => 'form-group'} do |f| %>
			  <p>
				<%= f.label :text %><br>
				<%= f.text_area :text, id: "new_task_text", :class  => 'form-control' %>
			  </p>			  
				<%= f.hidden_field :completed, :value => "FALSE" %>
			  <p>
				<%= f.submit %>
			  </p>
			<% end %>
   </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<% content_for :top_content do %>

  <div class="jumbotron">
    <div class="container">
	 <% if user_signed_in? %>
   

         <h1><%= current_user.name %>, Welcome to ToDoList!!</h1>		 
		 <h2>Tasks sumary:</h2>
		 <p>You have <%=current_user.tasks.size %> Total tasks!</p> 
		 <%= link_to("Manage Tasks", user_tasks_path(current_user)) %>
	
  <% else %>
	
      <h1>Welcome!</h1>
      <p>Login to start using the best ToDoList app EVER!!!</p>
      <p>
	    <%= link_to 'Log In', new_user_session_path, class: 'btn btn-primary btn-lg' %>
      </p>     
	  <p>Still not a user? Register now and join the FUN</p>
      <p>
        <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>	  
      </p>
    </div>
  </div>
        <% end %>

<% end %>